# Generated by Django 4.2 on 2023-07-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('des', models.TextField(blank=True, null=True)),
                ('em', models.IntegerField(default=5)),
                ('avatar', models.ImageField(upload_to='aksha')),
            ],
        ),
    ]
