# Generated by Django 4.2 on 2023-07-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stark', '0002_coursemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='em',
            field=models.IntegerField(choices=[(1, '<li><i class="fa fa-star"></i></li>'), (2, '<li><i class="fa fa-star"></i></li><li><i class="fa fa-star"></i></li>'), (3, '<li><i class="fa fa-star"></i></li><li><i class="fa fa-star"></i></li><li><i class="fa fa-star"></i></li>'), (4, '<li><i class="fa fa-star"></i></li><li><i class="fa fa-star"></i></li><li><i class="fa fa-star"></i></li><li><i class="fa fa-star"></i></li>'), (5, '<li><i class="fa fa-star"></i></li><li><i class="fa fa-star"></i></li><li><i class="fa fa-star"></i></li><li><i class="fa fa-star"></i></li><li><i class="fa fa-star"></i></li>')]),
        ),
    ]
